### PR TITLE
normalized 3d scaling for new models

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by poeschlr** [comment]
CP_Radial_D10.0mm_P2.50mm_P5.00mm and CP_Radial_D10.0mm_P5.00mm_P7.50mm
  - why is the footprint called differently to the new 3d file? (You removed the second P#.##mm from the 3d shapes name.)

If this is on purpose i can merge this. (For future pull requests: If you do something like this, just add a note to the description. Than we know that it was not a mistake.)

**Comment by Shackmeister** [comment]
those footprints are made as a dualfootprint for 2 different caps, I just changed the 3d path to refer to the smallest one of them (so we avoid duplicate models)

**Comment by poeschlr** [comment]
If there are different sizes, maybe we should split them into two footprints. Or at least use the larger model. (you can always put something in a confined space if it is smaller than originally planned. The other way round is not always possible.)

**Comment by Shackmeister** [comment]
not different sizes, different pin pitch, everything else is the same
the dualfootprint is on purpose. both footprints exist independently
does this make sense?

**Comment by jkriege2** [comment]
I would put the larger Pitch, the way I designed these is to accomodate the larger package, but allow for soldering also a narrower package ... So very possibly the small-pitch cap will also be in a smaller package.

Best,
JAN

**Comment by Shackmeister** [comment]
I can add the larger one but then Ill need a seperate model for these footprints since the caps need a slight rotation (do you know much?)

**Comment by Shackmeister** [comment]
I have now added the 2 missing caps
tht_cap

**Comment by Shackmeister** [comment]
@poeschlr @jkriege2 this is what you wanted right? any other comments?

**Comment by poeschlr** [comment]
Looks good now. I will merge this once https://github.com/KiCad/kicad-library/pull/1265 is merged.

**Comment by poeschlr** [comment]
I nearly forgot to merge this. Thanks for your contribution.

**Pull request merged**
