### PR TITLE
removed windows lineending

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by Shackmeister** [comment]
hmm any good way (perhaps scripted) to added the refdef?

**Comment by jkriege2** [comment]
You can use the fix-option of the `check_kicad_mod'-script (https://github.com/KiCad/kicad-library-utils/tree/master/pcb)

cu
JAN

**Comment by jkriege2** [comment]
PS: I won't have time in the next weeks/months to make STEP-files and possibly rework the 3D models ...

**Comment by Shackmeister** [comment]
Hey Jan I tried out the script and Im having trouble figuring out how to apply the script to a whole .pretty folder instead of just one kicad_mod file

regarding the 3d models I have so far made the new radial THT capacitors ready and made the script for generating the rect capacitors, adding parameters shouldnt take too long since you have them in your files :)
https://forum.kicad.info/t/3d-models-freecad/6270/27

**Comment by jkriege2** [comment]
Hi!

1. you can simply run the script with wildcards in the filename (e.g. `./*.kicad_mod`)
2. Some time ago there was a discussion on adding the height of each cap to the footprint name (i.e. add `_H25mm`...) ... maybe you can already add the height to the 3D models? And I can see whether I can change the footprint names in the next few weeks ... or if you have time ... ;-)

Best,
JAN

**Comment by Shackmeister** [comment]
So run the script inside the folder with the wildcard? 

Well those are pretty easily added perhaps we can even add the new kinds parameters to you footprint generator

**Comment by Shackmeister** [comment]
fixed it, please merge :)
will probably update the 3d scaling over the next few days but thats another story

**Pull request merged**
