### PR TITLE
updated for new CP_Axial 3d Models

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Have the 3D models been added for these at 1:1:1 scaling?

**Comment by Shackmeister** [comment]
Ill push them in a few minutes, found an improvement and is reexporting atm :)

**Comment by Shackmeister** [comment]
@SchrodingersGat now they are https://github.com/KiCad/packages3D/pull/91

**Comment by SchrodingersGat** [comment]
Thanks!

**Pull request merged**
