### PR TITLE
Rework lib and fix KLC issues

### PR DESCRIPTION
**Pull request by jkriege2**
- reworked the whole library
- completely new set of footprints + 3D symbols (see https://github.com/KiCad/kicad-library/pull/902)
- all KLC compliant
- all generated by scripts (see https://github.com/pointhi/kicad-footprint-generator/pull/18)
- contains many variants that were not available before
- most with docu, weblinks, ...
- 3-pin electrolytic capacitors
- snapIn electrolytic caps
- vertical&horizontal electrolytic caps
- standard box caps (MKT-style and MKS-style)
- horizontal round caps
- disc caps
- tantalic caps (droplets)
- footprints with two possible pin pitches

2017-01-11 18_34_38-3d viewer
2017-01-11 18_35_28-3d viewer

2017-01-11 18_43_01-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb
2017-01-11 18_43_29-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb
2017-01-11 18_44_02-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Great, nothing stands out as being wrong. I shall wait for https://github.com/KiCad/kicad-library/pull/902 before merging.

**Comment by jkriege2** [comment]
https://github.com/KiCad/kicad-library/pull/902 should be fixed ... please have a look, also at 
- https://github.com/KiCad/Capacitors_SMD.pretty/pull/12
- https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty/pull/10
as they all belong together

**Comment by SchrodingersGat** [comment]
Ping this again when https://github.com/KiCad/kicad-library/pull/902 is merged :)

**Comment by jkriege2** [comment]
Ping ;-)

**Comment by SchrodingersGat** [comment]
@jkriege2 there is an issue here that I did not notice before:

1. Model scaling should be 1:1:1 (model size will need to be changed)
1. Model name should include height (we can ignore the KLC that states they must be the same name as the footprint)

**Pull request merged**
