### PR TITLE
Add a couple additional axial electrolytic footprints

### PR DESCRIPTION
**Pull request by scanny**
I needed these for a project and wanted to get to know the kicad_mod format a bit better, so I whipped up a Python script to generate these for an arbitrary diameter, length, and pitch. The pads are aligned on a 20 mil (0.508mm) grid and other drawing is on a 10 mil (0.254mm) grid.

Let me know if you're interested in other sizes, I can generate them lickety-split :)

Thanks for KiCad, it's a great tool and I'm happy to contribute if I can :)

If these need any refinement just let me know, I can tweak my code to adapt to other requirements.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Steve,

Your footprints are great. If you could put the fp_text, fp_line and others on one line in the text file that would be great. Additionnally, if you want to generate all existing sizes, we would have one style for them all. Yours is better because of the polarity signs apparent after assembly.

BTW, did you see the scripts here?
https://github.com/KiCad/kicad-library-utils/tree/master/pcb
The kicad_mod might be of help to you.

Thanks!

**Comment by jkriege2** [comment]
is this included here to your satisfacction?
https://github.com/KiCad/Capacitors_THT.pretty/pull/12

**Comment by jkriege2** [comment]
can this be closed?
JAN

**Comment by CarlPoirier** [comment]
None of these sizes were included in your contribution, but no reply means satisfaction so I say you can close this.

**Pull request closed without merging**
