### PR TITLE
Added disk capacitor with diameter 7.5mm, tickness 2.5mm and pitch 5mm.

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by ricardocrudo** [comment]
@crackerizer please just fix the courtyard grid and it'll be great. Thanks

**Comment by crackerizer** [comment]
Done.

**Comment by ricardocrudo** [comment]
What "T" in C_Disc_D7.5_T2.5_P5 stands for?
please, set anchor to pad 1 in C_Radial_D20_L31_P10

**Comment by jkriege2** [comment]
This is included here: https://github.com/KiCad/Capacitors_THT.pretty/pull/12

**Comment by jkriege2** [comment]
available here: https://github.com/KiCad/Capacitors_THT.pretty/blob/master/C_Disc_D7.5mm_W2.5mm_P5.00mm.kicad_mod

**Pull request closed without merging**
